# syntax=docker.io/docker/dockerfile-upstream:1.27.0
# check=error=true

# Copyright (C) 2023 - present, Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker build --tag juergenzimmermann/patient:2026.10.1-alpine -f Dockerfile.alpine .
#               ggf. --no-cache
#
#           Windows:   Get-Content Dockerfile.alpine | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#           macOS:     cat Dockerfile.alpine | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#
#           docker debug juergenzimmermann/patient:2026.10.1-alpine
#           docker save juergenzimmermann/patient:2026.10.1-alpine > patient.tar

# https://docs.docker.com/engine/reference/builder/#syntax
# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# https://hub.docker.com/r/docker/dockerfile
# https://docs.docker.com/build/building/multi-stage
# https://testdriven.io/blog/docker-best-practices
# https://containers.gitbook.io/build-containers-the-hard-way
# https://wiki.debian.org/DebianReleases
# https://github.com/astral-sh/uv-docker-example/blob/main/multistage.Dockerfile
# https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile
# https://www.saaspegasus.com/guides/uv-deep-dive

# ARG: "build-time" Variable
# ENV: "build-time" und "runtime" Variable
ARG PYTHON_VERSION_UV=3.15-rc
ARG PYTHON_VERSION=3.15.0rc2
ARG UV_VERSION=0.12.20
ARG ALPINE_VERSION=3.24
ARG ALPINE_VERSION_UV=3.23

# ------------------------------------------------------------------------------
# S t a g e   b u i l d e r
# ------------------------------------------------------------------------------
FROM ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION_UV}-alpine${ALPINE_VERSION_UV} AS builder

WORKDIR /opt/app

# Enable bytecode compilation
# Copy from the cache instead of linking since it's a mounted volume
# Kein Python-Download, falls eine "managed" Python-Version verwendet wird,
# sondern in beiden Images denselben Python-Interpreter verwenden
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/opt/app/.venv

RUN <<EOF
# https://explainshell.com/explain?cmd=set+-eux
set -eux
# apk = Alpine Package Keeper
# https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper
# https://docs.alpinelinux.org/user-handbook/0.1a/Working/apk.html
# Die "Package Index"-Dateien neu synchronisieren
apk update
# Die neuesten Versionen der bereits installierten Packages installieren
apk upgrade

# ggf. Python fuer pg
# https://dl-cdn.alpinelinux.org/alpine/v3.23/main/x86_64
# https://dl-cdn.alpinelinux.org/alpine/v3.23/community/x86_64
# https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/gcc
# https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/g++
# https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/python3-dev
# https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/musl-dev
# https://pkgs.alpinelinux.org/package/v3.23/main/x86_64/linux-headers
apk --no-cache add gcc=15.2.0-r2 g++=15.2.0-r2 python3-dev=3.12.14-r0 musl-dev=1.2.5-r23 linux-headers=6.16.12-r0
EOF

# Install the project's dependencies using the lockfile and settings (siehe "[tool.uv]" in pyproject.toml)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml <<EOF \
    uv venv
    uv sync --frozen --no-install-project --no-default-groups --no-editable
EOF

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY LICENSE README.md pyproject.toml ./
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    uv sync --frozen --no-default-groups --no-editable

# ------------------------------------------------------------------------------
# S t a g e   f i n a l
# ------------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION} AS final

ARG APP_UID=10000
ARG APP_GID=10000

# Anzeige bei "docker inspect ..."
# https://specs.opencontainers.org/image-spec/annotations
# https://spdx.org/licenses
# MAINTAINER ist deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
LABEL org.opencontainers.image.title="patient" \
    org.opencontainers.image.description="Appserver patient mit Basis-Image Alpine" \
    org.opencontainers.image.version="2026.10.1-alpine" \
    org.opencontainers.image.licenses="GPL-3.0-or-later" \
    org.opencontainers.image.authors="Juergen.Zimmermann@h-ka.de"

# "working directory" fuer die Docker-Kommandos RUN, ENTRYPOINT, CMD, COPY und ADD
WORKDIR /opt/app

# https://unix.stackexchange.com/questions/217369/clear-apt-get-list
# https://medium.com/vantageai/how-to-make-your-python-docker-images-secure-fast-small-b3a6870373a0
RUN <<EOF
set -eux
# https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user
addgroup --gid ${APP_GID} app
adduser --uid ${APP_UID} --ingroup app --shell /bin/bash --no-create-home --disabled-password app
# User "app" als Owner fuer das working directory
chown -R ${APP_UID}:${APP_GID} /opt/app
EOF

USER ${APP_UID}:${APP_GID}

COPY --from=builder --chown=10000:10000 /opt/app ./

# Place executables in the environment at the front of the path
ENV PATH="/opt/app/.venv/bin:$PATH"

EXPOSE 8000

STOPSIGNAL SIGINT

ENTRYPOINT ["python", "-m", "patient"]
