# syntax=docker.io/docker/dockerfile-upstream:1.27.0
# check=error=true

# Copyright (C) 2023 - present, Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker build --tag juergenzimmermann/patient:2026.10.1-trixie -f Dockerfile.trixie .
#               ggf. --no-cache
#
#           Windows:   Get-Content Dockerfile.trixie | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#           macOS:     cat Dockerfile.trixie | docker run --rm --interactive hadolint/hadolint:v2.15.1-debian
#
#           docker debug juergenzimmermann/patient:2026.10.1-trixie
#           docker save juergenzimmermann/patient:2026.10.1-trixie > patient.tar

# https://docs.docker.com/engine/reference/builder/#syntax
# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# https://hub.docker.com/r/docker/dockerfile
# https://docs.docker.com/build/building/multi-stage
# https://testdriven.io/blog/docker-best-practices
# https://containers.gitbook.io/build-containers-the-hard-way
# https://wiki.debian.org/DebianReleases
# https://github.com/astral-sh/uv-docker-example/blob/main/multistage.Dockerfile
# https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile
# https://www.saaspegasus.com/guides/uv-deep-dive

# ARG: "build-time" Variable
# ENV: "build-time" und "runtime" Variable
ARG PYTHON_VERSION_UV=3.15-rc
ARG PYTHON_VERSION=3.15.0rc2
ARG UV_VERSION=0.12.20

# ------------------------------------------------------------------------------
# S t a g e   b u i l d e r
# ------------------------------------------------------------------------------
FROM ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION_UV}-trixie-slim AS builder

# Install the project into `/opt/app`
WORKDIR /opt/app

# Enable bytecode compilation
# Copy from the cache instead of linking since it's a mounted volume
# Kein Python-Download, falls eine "managed" Python-Version verwendet wird,
# sondern in beiden Images denselben Python-Interpreter verwenden
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=0 \
    UV_PROJECT_ENVIRONMENT=/opt/app/.venv \
    PATH="/root/.cargo/bin:$PATH"

RUN <<EOF
set -eux
# https://manpages.debian.org/trixie/apt/apt-get.8.en.html
# Die "Package Index"-Dateien neu synchronisieren
apt-get update --no-show-upgraded
# Die neuesten Versionen der bereits installierten Packages installieren
apt-get upgrade --yes --no-show-upgraded
# https://packages.debian.org/trixie/gcc
# https://packages.debian.org/trixie/curl
# https://packages.debian.org/trixie/libc6-dev
apt-get install --no-install-recommends --yes --show-progress curl=8.14.1-2+deb13u5 gcc=4:14.2.0-1 libc6-dev=2.41-12+deb13u4
# https://www.rust-lang.org/tools/install
curl --proto '=https' --tlsv1.3 --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile minimal --no-modify-path -y
EOF

# Install the project's dependencies using the lockfile and settings (siehe "[tool.uv]" in pyproject.toml)
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-default-groups --no-editable

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY LICENSE README.md pyproject.toml ./
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    uv sync --frozen --no-default-groups --no-editable

# ------------------------------------------------------------------------------
# S t a g e   f i n a l
# ------------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim-trixie AS final

ARG APP_UID=10000
ARG APP_GID=10000

# Anzeige bei "docker inspect ..."
# https://specs.opencontainers.org/image-spec/annotations
# https://spdx.org/licenses
# MAINTAINER ist deprecated https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
LABEL org.opencontainers.image.title="patient" \
    org.opencontainers.image.description="Appserver patient mit Basis-Image Slim Trixie" \
    org.opencontainers.image.version="2026.10.1-trixie" \
    org.opencontainers.image.licenses="GPL-3.0-or-later" \
    org.opencontainers.image.authors="Juergen.Zimmermann@h-ka.de"

RUN <<EOF
set -eux
# Die "Package Index"-Dateien neu synchronisieren
apt-get update
# Die neuesten Versionen der bereits installierten Packages installieren
apt-get upgrade --yes
apt-get autoremove --yes
apt-get clean --yes
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/*
EOF

# "working directory" fuer die Docker-Kommandos RUN, ENTRYPOINT, CMD, COPY und ADD
WORKDIR /opt/app

# https://unix.stackexchange.com/questions/217369/clear-apt-get-list
# https://medium.com/vantageai/how-to-make-your-python-docker-images-secure-fast-small-b3a6870373a0
RUN <<EOF
set -eux
# https://manpages.debian.org/bookworm/passwd/groupadd.html
# https://manpages.debian.org/bookworm/adduser/addgroup.html
groupadd --gid ${APP_GID} app
# https://manpages.debian.org/bookworm/passwd/useradd.html
# https://manpages.debian.org/bookworm/adduser/adduser.html
useradd --uid ${APP_UID} --gid ${APP_GID} --shell /bin/bash --no-create-home app
# User "app" als Owner fuer das working directory
chown -R ${APP_UID}:${APP_GID} /opt/app
EOF

# User "app" statt User "root"
USER ${APP_UID}:${APP_GID}

COPY --from=builder --chown=${APP_UID}:${APP_GID} /opt/app ./

# Place executables in the environment at the front of the path
ENV PATH="/opt/app/.venv/bin:$PATH"

EXPOSE 8000

STOPSIGNAL SIGINT

ENTRYPOINT ["python", "-m", "patient"]
