# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# https://peps.python.org/pep-0518
# https://peps.python.org/pep-0621/#example
# https://packaging.python.org/en/latest/specifications/pyproject-toml

# TOML (= Tom's Obvious Minimal Language) https://toml.io

# Aufruf:   uv run patient
#               uv run python -m patient
#               uv run fastapi dev src/patient
#               uv run uvicorn src.patient:app --http zttp --http2 --ssl-certfile=src\patient\config\resources\tls\certificate.crt --ssl-keyfile=src\patient\config\resources\tls\key.pem
#
#           curl -v --http2 --insecure `
#               --oauth2-bearer <access_token> `
#               https://localhost:8000/rest/1
#
#           uv run pytest
#               KEIN HTTP/2 https://github.com/psf/requests/issues/6856 (s. oben: curl)
#           uv run pytest -m rest
#           uv run pytest -k test_post_invalid_json
#
#           cd tests\lasttest
#           uvx locust
#
#           $env:USERPROFILE\.local\bin: uv, uvx, ruff, ty, pyrefly
#           ruff check --preview [--fix] src tests
#           ruff format --preview [--diff] [--check] src tests
#           ty check src tests/unit tests/integration
#           pyrefly check --verbose --output-format full-text
#           pyrefly report
#
#           uv tool upgrade ruff
#           uv tool upgrade ty
#           uv tool (un)install pyrefly --preview-features tool-install-locks [--prerelease allow]
#           uv tool (un)install yamllint
#           uv tool audit ruff ty pyrefly
#           uv tool dir
#               $env:APPDATA\uv\tools
#           uv check --all-extras
#
#           uv run mkdocs serve
#
#           uv lock --upgrade
#           uv sync --all-groups
#               uv pip list --outdated
#               uv tree --outdated --all-groups --depth=1
#               uv tree --invert --package pydantic
#               uv tree
#           uv audit [--no-dev]
#           uv python list
#
#           uvx library-skills
#               .agents/skills/fastapi/SKILL.md
#               .claude/skills/fastapi/SKILL.md
#               https://github.com/tiangolo/library-skills
#               https://fastapi.tiangolo.com/tutorial/#ai-agent-skills
#
#           uv build
#           uv publish --token <UV_PUBLISH_TOKEN>

[project]
name = "patient"
version = "2026.10.1"
description = "Beispiel mit FastAPI, PostgreSQL, Keycloak, Pydantic, Strawberry und uv"
readme = "README.md"
authors = [
    { name = "Juergen Zimmermann", email = "Juergen.Zimmermann@h-ka.de" },
]
maintainers = [
    { name = "Jürgen Zimmermann", email = "Juergen.Zimmermann@h-ka.de" },
]
requires-python = ">=3.15"
keywords = [
    "Python",
    "FastAPI",
    "ASGI",
    "REST",
    "GraphQL",
    "TLS",
    "Validierung",
    "OR-Mapping",
    "PostgreSQL",
    "OAuth2",
    "Keycloak",
    "Excel",
    "Logging",
    "TOML",
    "Test",
    "Codeanalyse",
    "Formatierung",
    "Dokumentation",
    "Buildsystem",
]
# https://pypi.org/classifiers
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Framework :: Pytest",
    "Framework :: MkDocs",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.15",
    "Topic :: Database",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Traffic Generation",
]
# https://spdx.org/licenses/GPL-3.0-or-later.html
# https://packaging.python.org/en/latest/specifications/license-expression
# https://packaging.python.org/en/latest/specifications/pyproject-toml/#license
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

dependencies = [
    # https://github.com/agronholm/anyio fuer Starlette
    "anyio>=4.15.1,<5.0.0",
    # https://github.com/python-cffi/cffi
    # Foreign Function Interface for Python calling C code, z.B. in cryptography
    "cffi>=2.1.1,<3.0.0",
    # https://cryptography.io fuer python-keycloak bzw. jwcrypto
    "cryptography>=49.0.0,<50.0.0",
    # Fuer Pydantic zur Validierung https://github.com/JoshData/python-email-validator
    "email-validator>=2.3.0,<3.0.0",
    # https://fastapi.tiangolo.com einschl. starlette, pydantic, uvicorn
    "fastapi>=0.141.1,<1.0.0",
    # https://github.com/latchset/jwcrypto genutzt von python-keycloak
    # TODO https://github.com/marcospereirampj/python-keycloak/issues/674
    "jwcrypto>=1.6.1,<2.0.0",
    # https://github.com/Delgan/loguru
    "loguru>=0.7.3,<1.0.0",
    # https://openpyxl.readthedocs.io
    "openpyxl>=3.1.5,<4.0.0",
    # Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
    # https://github.com/ijl/orjson
    "orjson>=3.12.0,<4.0.0",
    # https://github.com/prometheus/client_python
    "prometheus-client>=0.26.0,<1.0.0",
    # https://github.com/trallnag/prometheus-fastapi-instrumentator
    "prometheus-fastapi-instrumentator>=8.1.0,<9.0.0",
    # https://www.psycopg.org/psycopg3 https://github.com/psycopg/psycopg3
    "psycopg[binary,pool]>=3.3.6,<4.0.0",
    "psycopg-binary>=3.3.6,<4.0.0",
    "psycopg-pool>=3.3.3,<4.0.0",
    # Validierung https://github.com/pydantic/pydantic https://github.com/pydantic/pydantic/blob/main/pyproject.toml#L49
    "pydantic[email]>=2.13.5,<3.0.0",
    # "Core" fuer Pydantic, implementiert in Rust https://github.com/pydantic/pydantic-core
    "pydantic_core>=2.46.5,<3.0.0",
    # https://github.com/pwaller/pyfiglet
    "pyfiglet>=1.0.4,<2.0.0",
    # https://pyinstrument.readthedocs.io https://github.com/joerick/pyinstrument
    "pyinstrument>=5.1.3,<6.0.0",
    # https://pyjwt.readthedocs.io; genutzt im Handbuch von FastAPI
    # https://jwt.io/libraries?language=Python
    # python-keycloak nutzt jwcrypto
    #"PyJWT>=2.10.1,<3.0.0",
    # .env durch https://github.com/theskumar/python-dotenv
    "python-dotenv>=1.2.3,<2.0.0",
    # https://python-keycloak.readthedocs.io
    # Keycloak verschluesselt Passwoerter mit Argon2 (Sieger "Password Hashing Competition", 2013)
    # https://www.endpoint51.com/oauth-2-authorization-code-flow-python
    "python-keycloak>=7.1.1,<8.0.0",
    # https://github.com/Kludex/python-multipart fuer fastapi
    "python-multipart>=v0.0.32,<1.0.0",
    # fuer OpenAPI
    "PyYAML>=6.0.3,<7.0.0",
    # https://requests.readthedocs.io
    # fuer python-keycloak (und fuer eigene Integrationstests), auch genutzt von locust
    # einfach, synchron, blockierend
    # nutzt urllib fuer HTTP/1.1; urllib unterstuetzt auch HTTP/2
    # httpx genutzt von FastAPI
    "requests==2.34.2,<3.0.0",
    # https://www.sqlalchemy.org
    # free-threaded Python unterstuetzt ab 2.1
    "SQLAlchemy>=2.1.1,<3.0.0",
    # https://www.starlette.dev bei GitHub gleiche Benutzerkennung wie uvicorn und zttp
    "starlette>=1.7.0,<2.0.0",
    # https://strawberry.rocks https://github.com/strawberry-graphql/strawberry
    "strawberry-graphql>=0.327.7,<1.0.0",
    # https://github.com/astanin/python-tabulate
    "tabulate>=0.10.0,<1.0.0",
    # https://urllib3.readthedocs.io
    # fuer requests, seit 2024 HTTP/2 https://urllib3.readthedocs.io/en/stable/changelog.html#id19
    "urllib3>=2.8.0,<3.0.0",
    # https://www.uvicorn.dev bei GitHub gleiche Benutzerkennung wie Starlette und zttp
    "uvicorn>=0.54.0,<1.0.0",
    # https://github.com/Kludex/zttp  bei GitHub gleiche Benutzerkennung wie uvicorn und zttp
    "zttp>=0.0.34",
]

[project.scripts]
patient = "patient:main"

[build-system]
# https://docs.astral.sh/uv/concepts/build-backend/#using-the-uv-build-backend
requires = ["uv_build>=0.12.20,<1.0.0"]
build-backend = "uv_build"

[project.urls]
homepage = "https://www.h-ka.de"
documentation = "https://readthedocs.org"
repository = "https://github.com"
changelog = "https://github.com/juergenzimmermann/patient/blob/master/CHANGELOG.md"

# https://packaging.python.org/en/latest/specifications/dependency-groups
# https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements
# https://pip.pypa.io/en/stable/user_guide/#dependency-groups
# project.optional-dependencies ist laut https://peps.python.org/pep-0508 fuer optionale "extras"
# https://docs.astral.sh/uv/concepts/projects/dependencies/#optional-dependencies
[dependency-groups]
dev = [
    # FastAPI CLI
    "fastapi[standard]>=0.141.1,<1.0.0",
    # https://github.com/MagicStack/httptools genutzt von uvicorn[standard] fuer fastapi[standard]
    "httptools>=0.7.1,<1.0.0",
    # https://locust.io
    "locust>=2.46.6,<3.0.0",
    # genutzt von pytest, fastapi-cli, mkdocs-material
    "pygments>=2.20.0,<3.0.0",
    # https://pytest.org
    "pytest>=9.1.0,<10.0.0",
    # https://pytest-cov.readthedocs.io
    "pytest-cov>=7.1.0,<8.0.0",
    # https://github.com/pytest-dev/pytest-env
    "pytest-env>=1.7.1,<2.0.0",
    # https://github.com/pytest-dev/pytest-html
    "pytest-html>=4.2.0,<5.0.0",
    # https://github.com/pytest-dev/pytest-mock
    "pytest-mock>=3.16.0,<4.0.0",
    # https://saurabh-kumar.com/python-dotenv
    "python-dotenv>=1.2.2,<2.0.0",
]
doc = [
    # https://github.com/mkdocstrings/griffe
    # mkdocstrings-python > griffe
    "griffe>=2.3.0,<3.0.0",
    # https://github.com/Python-Markdown/markdown
    "Markdown>=3.11.0,<4.0.0",
    # https://mistune.lepture.com
    "mistune>=3.3.4,<4.0.0",
    # https://github.com/christo-ph/mkdocs_build_plantuml
    "mkdocs-build-plantuml-plugin>=2.1.0,<3.0.0",
    # https://squidfunk.github.io/mkdocs-material
    "mkdocs-material>=9.7.7,<10.0.0",
    # https://github.com/facelessuser/mkdocs-material-extensions
    "mkdocs-material-extensions>=1.3.1,<2.0.0",
    # https://www.mkdocs.org
    "mkdocs>=1.6.1,<2.0.0",
    # https://mkdocstrings.github.io https://mkdocstrings.github.io/python
    "mkdocstrings[python]>=1.0.6,<2.0.0",
    "mkdocstrings-python>=2.0.9,<3.0.0",
]
lint = [
    # http://pyrefly.org https://github.com/facebook/pyrefly
    "pyrefly>=1.4.0-dev.2,<2.0.0",
    # https://docs.astral.sh/ruff https://github.com/astral-sh/ruff
    "ruff>=0.16.9,<1.0.0",
    # https://github.com/astral-sh/ty
    "ty>=0.0.84,<1.0.0",
    "types-jwcrypto>=1.6.1.20260928,<2.0.0",
    "types-openpyxl>=3.1.5.20260827,<4.0.0",
    "types-tabulate>=0.10.0.20260508,<1.0.0",
    # https://github.com/adrienverge/yamllint
    "yamllint>=1.38.0,<2.0.0",
]

# https://coverage.readthedocs.io/en/latest/source.html
[tool.coverage.run]
include = ["src/patient/service/*"]

[tool.fastapi]
entrypoint = "patient.main:app"

# https://pyrefly.org/en/docs/configuration
[tool.pyrefly]
# project-includes = ["src", "tests"]
project-includes = ["src"]
python-version = "3.15"
# TODO frozendict https://github.com/facebook/pyrefly/issues/4994
required-version = ">=1.4.0-dev.2,<2.0.0"
min-severity = "warn"
preset = "strict"

# https://docs.pytest.org/en/stable/reference/customize.html
[tool.pytest.ini_options]
minversion = "9.1.0"
# fuer Unit-Tests
pythonpath = ["src", "tests/integration"]
testpaths = ["tests/unit/patient/service", "tests/integration"]
# -m: nur Tests mit dem spezifizierten _Marker_ ausführen
# -r A: zusaetzliche Zusammenfassung anzeigen (A = All)
# --html erfordert pytest-html
# --cov erfordert pytest-cov
addopts = "--html=report.html --cov --cov-report=html"
markers = [
    "rest: REST-Schnittstelle",
    "get_request: GET-Requests",
    "query_request: QUERY-Requests",
    "post_request: POST-Requests",
    "post_request_success: POST-Requests",
    "put_request: PUT-Requests",
    "delete_request: DELETE-Requests",
    "login: Login mit der REST-Schnittstelle",
    "health: Health des Servers ueberpruefen",
    "graphql: GraphQL-Schnittstelle",
    "query: Queries bei GraphQL",
    "mutation: Mutations bei GraphQL",
    "simple: Einfache Tests mit True und False",
    "unit",
    "unit_find_by_id",
    "unit_find",
    "unit_create",
]

[tool.pytest_env]
# Zur Fehlersuche in Unit-Tests ggf. auskommentieren
# LOGURU_LEVEL = "INFO"

[tool.ruff]
preview = true

[tool.ruff.lint]
select = [
    # https://docs.astral.sh/ruff/default-rules
    "YTT",   # flake8-2020 https://pypi.org/project/flake8-2020
    "ASYNC", # flake8-async https://github.com/python-trio/flake8-async
    "S",     # flake8-bandit https://github.com/tylerwince/flake8-bandit
    "BLE",   # flake8-blind-except https://github.com/elijahandrews/flake8-blind-except
    "B",     # flake8-bugbear https://github.com/PyCQA/flake8-bugbear
    "C4",    # flake8-comprehensions https://github.com/adamchainz/flake8-comprehensions
    "DTZ",   # flake8-datetimez https://github.com/pjknkda/flake8-datetimez
    "T10",   # flake8-debugger https://github.com/JBKahn/flake8-debugger
    "EXE",   # flake8-executable https://github.com/xuhdev/flake8-executable
    "FA",    # flake8-future-annotations https://github.com/TylerYep/flake8-future-annotations
    "INT",   # flake8-gettext https://github.com/cielavenir/flake8_gettext
    "ISC",   # flake8-implicit-str-concat https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat
    "LOG",   # flake8-logging https://github.com/adamchainz/flake8-logging
    "G",     # flake8-logging-format https://pypi.org/project/flake8-logging-format
    "PIE",   # flake8-pie https://github.com/sbdchd/flake8-pie
    "PYI",   # flake8-pyi https://github.com/pycqa/flake8-pyi
    "PT",    # flake8-pytest-style https://github.com/m-burst/flake8-pytest-style
    "RET",   # flake8-return https://github.com/afonasev/flake8-return
    "SIM",   # flake8-simplify https://github.com/MartinThoma/flake8-simplify
    "TC",    # flake8-type-checking https://github.com/snok/flake8-type-checking
    "PTH",   # flake8-use-pathlib https://gitlab.com/RoPP/flake8-use-pathlib
    "FLY",   # flynt https://github.com/ikamensh/flynt
    "I",     # isort https://github.com/PyCQA/isort
    "N",     # pep8-naming https://github.com/PyCQA/pep8-naming
    "PERF",  # Perflint https://github.com/tonybaloney/perflint
    "E",     # pycodestyle https://github.com/pycqa/pycodestyle
    "W",     # pycodestyle (warning)
    "D",     # pydocstyle https://github.com/jsh9/pydoclint
    "F",     # Pyflakes https://github.com/PyCQA/pyflakes
    "PGH",   # pygrep-hooks https://docs.astral.sh/ruff/default-rules/#pygrep-hooks-pgh
    "PL",    # Pylint https://pypi.org/project/pylint
    "UP",    # pyupgrade https://github.com/asottile/pyupgrade
    "FURB",  # refurb https://github.com/dosisod/refurb
    "RUF",   # Ruff-specific rules https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "TRY",   # tryceratops https://github.com/guilatrova/tryceratops
    # https://docs.astral.sh/ruff/rules
    "FAST", # FastAPI
    "FBT",  # flake8-boolean-trap https://github.com/pwoolvett/flake8_boolean_trap
    "A",    # flake8-builtins https://github.com/gforcada/flake8-builtins
    "COM",  # flake8-commas https://github.com/PyCQA/flake8-commas
    "RSE",  # flake8-raise https://github.com/jdufresne/flake8-raise
    "SLF",  # flake8-self
    "TID",  # flake8-tidy-imports https://github.com/adamchainz/flake8-tidy-imports
    "ARG",  # flake8-unused-arguments https://github.com/nhoad/flake8-unused-arguments
]
ignore = [
    # "multi-line-summary-first-line" statt "incorrect-blank-line-before-class" und "multi-line-summary-second-line"
    "incorrect-blank-line-before-class",
    "multi-line-summary-second-line",
    # https://github.com/astral-sh/ruff/issues/9216
    "missing-trailing-comma",
    "no-self-use",
    # UTF-8 ist default ab Python 3.15
    "unspecified-encoding",
]

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["assert", "undocumented-public-function"]
"tests/integration/**/*_test.py" = ["raise-vanilla-args"]
"tests/unit/patient/service/*_test.py" = ["unused-lambda-argument"]

[tool.ruff.lint.pylint]
max-statements-in-try = 7

# https://docs.astral.sh/ty/reference/configuration
[tool.ty.environment]
# https://docs.astral.sh/ty/reference/configuration/#python
python = "./.venv"
# https://docs.astral.sh/ty/modules
root = ["./src", "./tests/unit", "./tests/integration"]

[tool.uv]
required-version = ">= 0.12.20"
# https://docs.astral.sh/uv/concepts/preview
# https://docs.astral.sh/uv/reference/settings/#preview
preview-features = [
    "add-bounds",
    "audit-command",
    "centralized-project-envs",
    "check-command",
    # https://github.com/astral-sh/uv/pull/19693
    # $env:LOCALAPPDATA\uv\cache\archive-v0
    "content-addressed-cache",
    "detect-module-conflicts",
    "format-command",
    "json-output",
    "malware-check",
    "tool-install-locks",
]
# https://docs.astral.sh/uv/reference/settings/#add-bounds
add-bounds = "major"
# https://docs.astral.sh/uv/reference/settings/#prerelease
#prerelease = "allow"
# https://docs.astral.sh/uv/reference/settings/#default-groups
# VORSICHT: in Dockerfile "--no-default-groups" bei "uv sync"
default-groups = "all"

[tool.uv.pip]
# https://docs.astral.sh/uv/reference/settings/#pip_exclude-newer
exclude-newer = "1 day"
# https://docs.astral.sh/uv/reference/settings/#pip_extra
extra = ["dev", "doc", "lint"]
# https://docs.astral.sh/uv/reference/settings/#pip_all-extras
all-extras = true
