' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "patient" {
  [patient_router]
  [patient_write_router]
  [schema]

  [patient_read_service]
  [patient_write_service]

  [patient_repository]

  [mailer]
}


cloud {
    [SQLAlchemy]
}

cloud {
    [smtp]
}

database "DB patient" {
    [Tabelle patient]
    [Tabelle adresse]
    [Tabelle rechnung]
}

node {
    [Mailserver]
}

RESTClient ~~> [patient_router]
RESTClient ~~> [patient_write_router]
GraphQLClient ~~> [schema]

[patient_router] ..> [patient_read_service]
[patient_write_router] ..> [patient_write_service]
[schema] ..> [patient_read_service]
[schema] ..> [patient_write_service]
[patient_read_service] ..> [patient_repository]
[patient_write_service] ..> [patient_repository]

[patient_repository] ~~> [SQLAlchemy]
[SQLAlchemy] ~~> [Tabelle patient]
[SQLAlchemy] ~~> [Tabelle adresse]
[SQLAlchemy] ~~> [Tabelle rechnung]

[patient_write_service] ..> [mailer]
[mailer] ~~> [smtp]
[smtp] ~~> [Mailserver]

footer (c) Jürgen Zimmermann

@enduml
